---
# tasks file for prepare-web-content

- name: install the 'Development tools' package group
  yum:
    name: "@Development tools"
    state: present

# Strictly speaking, we don't need the selinux modules at this early stage,
# but having them will help the app-AfterInstall playbook avoid delays.
- name: Ensure firewall and selinux modules are present
  package: name={{item}} state=present
  with_items:
      - checkpolicy
      - firewalld
      - policycoreutils-python
      - policycoreutils
      - python-firewall

- name: Open firewalld port for http
  firewalld:
    service: http
    zone: drop
    permanent: true
    state: enabled

- name: Open firewalld port for http in public zone
  firewalld:
    service: http
    zone: public
    permanent: true
    state: enabled

- name: Reload service firewalld
  service:
    name: firewalld
    state: reloaded

- name: Stop and disable nginx, as it should start off disabled
  service:
    name: nginx
    enabled: no
    state: stopped

